version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
#  migrate:
#    image: migrate/migrate
#    depends_on:
#      - database
#    volumes:
#      - C:/Users/ilya.sachek/golang-rest-api/db/migrations:/database
#    command:
#      [ "-path", "/database", "-database",  "postgres://golang-rest-api:golang-rest-api_pass@database:5432/golang-rest-api_db?sslmode=disable", "up" ]
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "8080:8080"
volumes:
  data: