version: "3.7"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - data:/var/lib/postgresql/data
  migrate:
    image: migrate/migrate
    depends_on:
      - database
    volumes:
      - ./migrations:/database
    command:
      [ "-path", "/database", "-database",  "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:${DB_PORT}/${POSTGRES_DB}?sslmode=disable", "up" ]
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./wait-for-postgres.sh db ./restapi
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
volumes:
  data:
